Missing "time.h" lib.
"time()" function cannot implemented without "time.h" library.
--------------------------------------------------------------------
rand.cpp: In function 'void setSeed()':
rand.cpp:5:10: error: 'time' was not declared in this scope
  time(&tm);
          ^
make: *** [rand.o] Error 1